In [40]:
import pandas as pd
import numpy as np
df = pd.read_csv("C:/Users/Mehmet Nur Kavan/Desktop/advertising/advertising.csv")

In [41]:
df = df.iloc[:,1:len(df)] #bağımız değişken
df.head()

TV  radio  newspaper  sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [42]:
x= df.drop("sales", axis=1) # bağımsız değişkenleren bağımlı oluak olan salesi cıakrttık
y= df[["sales"]] # bağlı değişkeni y ye atadık  y= df["sales"] şeklinde ike nnpy dizisi olarak vardı ama [[]] kullanara  data frame yaptık

In [43]:
y.head()

sales
0   22.1
1   10.4
2    9.3
3   18.5
4   12.9

In [44]:
x.head()

TV  radio  newspaper
0  230.1   37.8       69.2
1   44.5   39.3       45.1
2   17.2   45.9       69.3
3  151.5   41.3       58.5
4  180.8   10.8       58.4

In [45]:
print(type(x))
print(type(y))

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>


Statsmodels ile model kurmak

In [46]:
import statsmodels.api as sm

In [47]:
lm= sm.OLS(y, x)  # lineear model(lm)   # ols regresyon için gerkeli

In [48]:
model = lm.fit()

model.smmary ile

r karesini görüyoruz. bağımsız değişkenlerle baımlı değişkeniaçıklaam oranı

bu summary kısmı çok öenmli yorumlayabilemn gerekir


In [49]:
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                                 OLS Regression Results                                
=======================================================================================
Dep. Variable:                  sales   R-squared (uncentered):                   0.982
Model:                            OLS   Adj. R-squared (uncentered):              0.982
Method:                 Least Squares   F-statistic:                              3566.
Date:                Mon, 23 Dec 2024   Prob (F-statistic):                   2.43e-171
Time:                        08:40:55   Log-Likelihood:                         -423.54
No. Observations:                 200   AIC:                                      853.1
Df Residuals:                     197   BIC:                                      863.0
Df Model:                           3                                                  
Covariance Type:            nonrobust                                                  
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
TV             0.0538      0.001     40.507      0.000       0.051       0.056
radio          0.2222      0.009     23.595      0.000       0.204       0.241
newspaper      0.0168      0.007      2.517      0.013       0.004       0.030
==============================================================================
Omnibus:                        5.982   Durbin-Watson:                   2.038
Prob(Omnibus):                  0.050   Jarque-Bera (JB):                7.039
Skew:                          -0.232   Prob(JB):                       0.0296
Kurtosis:                       3.794   Cond. No.                         12.6
==============================================================================

Notes:
[1] R² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

Scikit learn ile model kurmak

In [50]:
from sklearn.linear_model import LinearRegression
lm= LinearRegression()

In [51]:
model=lm.fit(x,y)

In [52]:
model.intercept_

array([2.93888937])

In [53]:
model.coef_

array([[ 0.04576465,  0.18853002, -0.00103749]])

Tahmin

Sales= 2.29 + TV*0.04 + radio* 0.19 -newspaper* 0.001

bu 2.2

In [54]:
2.94 + 30 * 0.04 + 10 * 0.19 - 40 * 0.001

5.999999999999999

In [55]:
yeni_veri= [[30],[10],[40]]
yeni_veri = pd.DataFrame(yeni_veri).T  
#! burdaki T colums olarak almamzı sağladı. bide arrayi Dataframe yaptik
yeni_veri

0   1   2
0  30  10  40

In [56]:
# Tahmin yapma
tahmin = model.predict(yeni_veri)
print("Tahmin Edilen Değer:", tahmin)

Tahmin Edilen Değer: [[6.15562918]]


c:\Users\Mehmet Nur Kavan\anaconda3\lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


In [57]:
from sklearn.metrics import mean_squared_error

In [58]:
y.head()

sales
0   22.1
1   10.4
2    9.3
3   18.5
4   12.9

In [59]:
model.predict(x)[0:10]

array([[20.52397441],
       [12.33785482],
       [12.30767078],
       [17.59782951],
       [13.18867186],
       [12.47834763],
       [11.72975995],
       [12.12295317],
       [ 3.72734086],
       [12.55084872]])

In [60]:
MSE = mean_squared_error(y, model.predict(x))
# y gerçek değer ile tahmin değerleri
# tahmin edilen değer ile gerçek değer arasındaki farkın karesinin ortalamasıdır
MSE

2.784126314510936

In [61]:
RMSE = np.sqrt(MSE)
# MSE'nin kareköküdür. Hatayı orijinal ölçekte gösterir.
RMSE

1.6685701407225697

Model Turing(Model Doğrulama)

In [62]:
from sklearn.model_selection import train_test_split

In [63]:
# verimizi20 ye 80 oalrka bölüyoz
x_train, x_test, y_train, y_test= train_test_split(x, y, test_size=0.20, random_state = 99)

In [64]:
x_train.head()  # x_train trainin in bağımsız değişkenleri

TV  radio  newspaper
16    67.8   36.6      114.0
51   100.4    9.6        3.6
97   184.9   21.0       22.0
164  117.2   14.7        5.4
71   109.8   14.3       31.7

In [65]:
y_train.head() # y_train trainin bağımlı değişkenleri

sales
16    12.5
51    10.7
97    15.5
164   11.9
71    12.4

In [66]:
x_test.head() # x_test testin bağımsız değişkenleri

TV  radio  newspaper
135  48.3   47.0        8.5
127  80.2    0.0        9.2
191  75.5   10.8        6.0
66   31.5   24.6        2.2
119  19.4   16.0       22.3

In [67]:
y_test.head() # y_test testin bağımlı değişkneleri

sales
135   11.6
127    8.8
191    9.9
66     9.5
119    6.6

In [68]:
lm=LinearRegression()
lm.fit(x_train, y_train) # trainni x_train(bağımsız değişkeni), ve trainn y_train(bağımlı değişkeni)

LinearRegression()

In [69]:
# eğitim hatası
np.sqrt(mean_squared_error(y_train, model.predict(x_train)))
#x_traindeki değerleri tahmin de buunup y_traindeki ike karşılaştıracaz

1.7244414935853614

In [70]:
# test hatası
np.sqrt(mean_squared_error(y_test, model.predict(x_test)))

1.4233192591119648

k- katlı cross validation

Veri kümesi, eğitim ve test veri setlerine bölünerek birkaç kez (burada cv=10, yani 10 katlı) test edilir.

In [71]:
from sklearn.model_selection import cross_val_score
cross_val_score(model, x_train, y_train, cv=10, scoring= "neg_mean_squared_error")

array([-2.1019073 , -2.48953197, -3.09704214, -2.34694216, -3.68175761,
       -1.8691401 , -3.18173007, -4.1927349 , -2.17128376, -8.03821974])

In [72]:
# train setine karşılık ortlaam hatamız
np.mean(-cross_val_score(model, x_train, y_train, cv=10, scoring= "neg_mean_squared_error"))

3.3170289742341255

In [73]:
#cv ile mse değerimiz.
np.sqrt(np.mean(-cross_val_score(model, x_train, y_train, cv=10, scoring= "neg_mean_squared_error")))

1.8212712522395245

In [74]:
# cros v ile sınama testi yünetimimini karşılaştırmak için
np.sqrt(np.mean(-cross_val_score(model, x, y, cv=10, scoring= "neg_mean_squared_error")))

1.7492763126843385